apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication
  template:
    metadata:
      labels:
        app: communication
    spec:
      containers:
        - name: communication
          image: us.gcr.io/dev-expert-platform/communication
          env:
            - name: MONGO_URI
              value: 'mongodb://communication-mongo-srv:27017/communication'
---
apiVersion: v1
kind: Service
metadata:
  name: communication-socket-srv
spec:
  selector:
    app: communication
  ports: 
    - name: communication
      protocol: TCP
      port: 5002
      targetPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: communication-srv
spec:
  selector:
    app: communication
  ports: 
    - name: communication
      protocol: TCP
      port: 5003
      targetPort: 5003